# Generated by Django 6.0.5 on 2026-05-16 23:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('normal', 'Normal'), ('alerta', 'Alerta'), ('critico', 'Crítico')], max_length=10)),
                ('chuva_mm', models.FloatField()),
                ('saturacao', models.FloatField()),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('webhook', 'Webhook')], max_length=10)),
                ('destinatario', models.CharField(help_text='E-mail, telefone ou URL do webhook', max_length=200)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falha', 'Falha'), ('ignorado', 'Ignorado')], default='pendente', max_length=10)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('erro_detalhe', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('webhook', 'Webhook')], max_length=10)),
                ('destinatario', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('notificar_alerta', models.BooleanField(default=True, verbose_name='Notificar nível Alerta')),
                ('notificar_critico', models.BooleanField(default=True, verbose_name='Notificar nível Crítico')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuração de Alerta',
                'verbose_name_plural': 'Configurações de Alertas',
            },
        ),
    ]
