# Generated by Django 6.0.5 on 2026-05-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=50)),
                ('chuva_mm', models.FloatField()),
                ('saturacao', models.FloatField()),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('alerta', 'Alerta'), ('critico', 'Crítico')], max_length=10)),
                ('populacao', models.CharField(max_length=20)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'ordering': ['-chuva_mm'],
            },
        ),
    ]
