# Generated by Django 6.0.5 on 2026-05-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('Escola', 'Escola'), ('Ginásio', 'Ginásio'), ('Igreja', 'Igreja'), ('Centro', 'Centro')], max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Abrigo',
                'verbose_name_plural': 'Abrigos',
                'ordering': ['bairro', 'nome'],
            },
        ),
    ]
